### ISSUE TITLE
What is the point of the $user and $group parameters?

### ISSUE THREAD

**Issue by TJM** [Dynatrace/Dynatrace-OneAgent-Puppet#14]
The `$user` and `$group` parameters appear to provide a way to define who the agent should run as, but, based on our testing, Dynatrace creates its own "dt_user" during installation, thus the only thing these parameters actually seem to get used for is who will own the downloaded installation file (which should be temporary anyhow).

I propose that we get rid of these parameters and all the unnecessary confusion they cause.

**Comment by luisescobar89** [comment]
fixed on latest version
