### ISSUE TITLE
dynatraceoneagent::resources::restart_services_hook is broken

### ISSUE THREAD

**Issue by TJM** [Dynatrace/Dynatrace-OneAgent-Puppet#16]
The class dynatraceoneagent::resources::restart_services_hook tries to call one of the following, based on kernel:

* oneagent::resources::linux_restartservice_initd
* oneagent::resources::windows_restartservice

For Windows, it looks like we may just need to fix the name of the module from "oneagent" to "dynatraceoneagent" 

For Linux, in addition to fixing the name of the module ("oneagent" to "dynatraceoneagent") as above, but also the linux_restartservice_initd does not exist. In addition to that, restarting services with initd is probably not the right tact.

For both of these, they should allow you specify a list of services to *notify*. It would appear that this is actually setup for otherwise unmanaged services, and it is doing it "the hard way" ... its messy and should probably just be removed all together.

**Comment by luisescobar89** [comment]
added reboot functionality on last version
