### ISSUE TITLE
since dynatrace doesnt want to support this...

### ISSUE THREAD

**Issue by bostrowski13** [Dynatrace/Dynatrace-OneAgent-Puppet#18]
I forked this module and rolled in the 3 PRs for #13 #11 #12 and #9 

I also updated the metadata dependencies to latest modules versions.  tested in my qa env and everything worked fine.

https://github.com/bostrowski13/Dynatrace-OneAgent-Puppet

**Comment by TJM** [comment]
@bostrowski13 We were thinking of doing the same thing. Watch out, we discovered as part of #15 that the "platform" discovery doesn't actually work, luckily on Linux the binaries.json reports both the 32 bit and 64 bit binaries are installed. This module would be a good "lab" for a puppet class. ;)
