### ISSUE TITLE
Add support for necessary / best practice switches

### ISSUE THREAD

**Issue by agardnerIT** [Dynatrace/Dynatrace-OneAgent-Puppet#19]
Add installer support for the required and best practice switches. Namely:

```
APP_LOG_CONTENT_ACCESS=1
INFRA_ONLY=0
HOST_GROUP=MyValue
```

These are specified as command line args as the end of the installer string:

For example:
`sudo /bin/sh/oneagent.sh APP_LOG_CONTENT_ACCESS=1 INFRA_ONLY=0 HOST_GROUP=MyApp_Dev`

**Comment by luisescobar89** [comment]
Added on last release
