### ISSUE TITLE
Remove notify resource message for case when not rebooting

### ISSUE THREAD

**Issue by costco-kynelson** [Dynatrace/Dynatrace-OneAgent-Puppet#21]
After resolving [#Issue 16](https://github.com/Dynatrace/Dynatrace-OneAgent-Puppet/issues/16), a notify resource was adding when reboot is false (the default case).

https://github.com/Dynatrace/Dynatrace-OneAgent-Puppet/blob/ec1b26dff18188c0fc105f2a0d6159b8eee6f069/manifests/service.pp#L57

This will appear in the runtime log every run when reboot is set to false. We don't need to be notified the host isn't being rebooted every run. Notify resources like these end up being noise in Puppet runtime log.

Suggestion would be to switch to a code comment or remove the _else_ clause altogether.

**Comment by luisescobar89** [comment]
debug message removed on release-1.0.0
