### ISSUE TITLE
switching from full stack to infrastructre mode and vice versa not working 

### ISSUE THREAD

**Issue by thatsk** [Dynatrace/Dynatrace-OneAgent-Puppet#33]
if you change 
```
        oneagent_params_hash  => {
            'INFRA_ONLY'             => '0',
            'APP_LOG_CONTENT_ACCESS' => '1',
            'HOST_GROUP'             => 'PUPPET_WINDOWS',
            'INSTALL_PATH'           => 'C:\Test Directory',
```
if you wish to change to fullstack you need to first uninstall manually and then install it again. This should be driven by puppet.

**Comment by thatsk** [comment]
@luisescobar89

**Comment by thatsk** [comment]
if we set infra_only to 1 it should uninstall first dynatraceonagent and reinstall with new params

**Comment by luisescobar89** [comment]
@thatsk thanks for reporting the issue, the [onagentctl](https://www.dynatrace.com/support/help/setup-and-configuration/dynatrace-oneagent/oneagent-configuration-via-command-line-interface/) will be supported in future releases which will allow OneAgent configuration updates post install

**Comment by luisescobar89** [comment]
Feature now supported on [release 1.5.0](https://github.com/Dynatrace/Dynatrace-OneAgent-Puppet/releases/tag/1.5.0)
