### ISSUE TITLE
zero length installer

### ISSUE THREAD

**Issue by TJM** [Dynatrace/Dynatrace-OneAgent-Puppet#34]
If the download fails for any reason (typo in token), the puppet code https://github.com/Dynatrace/Dynatrace-OneAgent-Puppet/blob/c38f502f32c01baef414fb07b15426a9e79a9457/manifests/install.pp#L40-L44 creates a zero length file for the installer, and then the install script returns 0 (success) (executing a blank shell script is successful apparently) and more config errors ensue. There should probably be a require on the file resource to make sure the archive completed successfully before creating an empty executable file. Additionally, instead of making the file executable, you could just exec "bash" and make the script file be an argument, which eliminates the need to make the script executable.

Once the zero length installer exists, even fixing the URL doesn't seem to resolve the problem, you have to login and manually remove the /tmp/Dynatrace-OneAgent-Linux.....sh file. 

On a related note, the default directory should probably not be /tmp. A secure built server will not allow executing anything in /tmp. At least you provided a parameter for that, but again if you run `bash /tmp/whatever.sh (otherArgs)`, that should eliminate that problem as well.

**Comment by costco-kynelson** [comment]
I have ran into this same issue. The File[$download_path] resource needs to require on the Archive[$download_path] resource so it doesn't create the file if the Archive resource fails.

After fixing the tpyo/issue, I added an Exec resource to check if the downloaded file was 0 bytes and deleting it to force Puppet to download again. At the module level, the clean way to fix if you're using a local repository would be to update the module to add the Archive checksum parameters and add the checksum so Puppet knows to re-download. The module option is to test if the URL is valid with a Ruby function and halt the download.

We also have restrictions on /tmp. You can specify the 'download_dir' parameter for an alternative directory. I chose to create a '/opt/dynatrace/installer' directory for this purpose.

**Comment by luisescobar89** [comment]
@TJM @costco-kynelson thanks both for the great feedback, this issue should now be addressed on [Release 1.6.0](https://github.com/Dynatrace/Dynatrace-OneAgent-Puppet/releases/tag/1.6.0)
