### ISSUE TITLE
Downloaded installer appends release version

### ISSUE THREAD

**Issue by phmcguin** [Dynatrace/Dynatrace-OneAgent-Puppet#4]
init.pp assumes the file will be called oneagent-Windows.msi or oneagent-Linux.sh but really the file name looks more like Dynatrace-OneAgent-Windows-1.139.179.exe/Dynatrace-OneAgent-Linux-1.139.179.sh and this filename changes with each new version release.

**Comment by TJM** [comment]
This doesn't appear to be the case anymore, the "current" code sets the destination filename.

**Comment by luisescobar89** [comment]
fixed in last version
