### ISSUE TITLE
--restart-service also needed for --set-network-zone

### ISSUE THREAD

**Issue by ianssoftcom** [Dynatrace/Dynatrace-OneAgent-Puppet#40]
The set-network-zone in dynatraceoneagent::config does not include restart-service although most others do

> /opt/dynatrace/oneagent/agent/tools/oneagentctl --set-network-zone=$(cat /var/lib/dynatrace/oneagent/agent/config/puppet/networkzone.conf)
> Configuration changes were not applied, OneAgent service must be stopped first. You may use --restart-service to automate the process

#39 is a better solution (consolidate service restarts), as long as set-network-zone is also included

**Comment by luisr-escobar** [comment]
fixed on [release 1.7.0](https://github.com/Dynatrace/Dynatrace-OneAgent-Puppet/tree/1.7.0)
