### ISSUE TITLE
uninstall is not implemented

### ISSUE THREAD

**Issue by TJM** [Dynatrace/Dynatrace-OneAgent-Puppet#41]
We want to ensure => absent, but that doesn't appear to be there.

**Comment by TJM** [comment]
WORKAROUND: use bolt or puppet tasks exec to run the uninstall script ... it probably *could* be added as a task in this module, but it would probably be a good idea to implement an "uninstall" either way

**Comment by luisr-escobar** [comment]
@TJM for Linux/AIX this is implemented [here](https://github.com/Dynatrace/Dynatrace-OneAgent-Puppet/blob/master/manifests/config.pp#L39), it uses the $package_state parameter to determine if the uninstall script should be executed

**Comment by TJM** [comment]
@luisr-escobar - Thanks, you might add that to the documentation, since you are not following the "normal" pattern of using `ensure =>` :)

**Comment by luisr-escobar** [comment]
yes good point we can probably add that to the examples but it is referenced here [REFERENCE.md](https://github.com/Dynatrace/Dynatrace-OneAgent-Puppet/blob/master/REFERENCE.md#package_state)

**Comment by TJM** [comment]
> yes good point we can probably add that to the examples but it is referenced here [REFERENCE.md](https://github.com/Dynatrace/Dynatrace-OneAgent-Puppet/blob/master/REFERENCE.md#package_state)

Right, sorry about that. I didn't see that doc (my bad). Can you please add the word "uninstall" in there, or as you say add uninstalling as an example to the main README.md. 

Thanks in advance,
Tommy
