### ISSUE TITLE
Ability to specify user and group during Install

### ISSUE THREAD

**Issue by weaverslodge** [Dynatrace/Dynatrace-OneAgent-Puppet#43]
I'm not. sure if there is a way of doing this through the module but if there is I can't find it. I can see a global owner and group but I'm not sure that these are the way to do this. I'm probably being stupid so please be gentle with me

**Comment by luisr-escobar** [comment]
@weaverslodge you can set any supported oneagent install parameters based on your OS via the $oneagent_params_hash like [user](https://www.dynatrace.com/support/help/shortlink/linux-custom-installation#-user-) or [group](https://www.dynatrace.com/support/help/shortlink/linux-custom-installation#-group-)
