### ISSUE TITLE
Question about staged usage

### ISSUE THREAD

**Issue by weaverslodge** [Dynatrace/Dynatrace-OneAgent-Puppet#44]
The environment that I have has very limited externally connected servers. I'd like to use the module for deployment and I have been trying to figure out how I can use our deployment server to download the agent install script through the module but not install it and then use the module to do the installation on the non-connected servers in a slightly different way. It seems that if the install script is already in the download directory then it doesn't go and get another version which helps but I can't figure out a way to get the module just to do the download piece. 

I'm not sure I've made what I want to. do clear but hopefully I have - Is there any way I can do this using the module as is ?

**Comment by luisr-escobar** [comment]
@weaverslodge by default if the `$package_state` parameter is set to present, this module will download and install the OneAgent, for your usecase there are 2 options I can think of:
1) Pass an invalid install parameter to the module which will cause the installation to fail but the OneAgent installer script will still be downloaded.
2) Set the `$package_state` to absent which will skip the installation but you would need to change/remove the condition on [this](https://github.com/Dynatrace/Dynatrace-OneAgent-Puppet/blob/master/manifests/download.pp#L31) line.
