### ISSUE TITLE
install.bat missing switches

### ISSUE THREAD

**Issue by phmcguin** [Dynatrace/Dynatrace-OneAgent-Puppet#7]
Install.bat uses msiexec installer.msi without the SERVER, TENANT, TENANT_TOKEN switches that are required to install using the OneAgent-Windows-verXYZ.msi file

**Comment by TJM** [comment]
The install.sh was also missing the ability to provide command line arguments (switches). I have added this capability in PR #10 . Let me know what you think. It currently accepts an "array" of arguments, so that you can specify them at different levels of hieradata. (and use a merge lookup)

**Comment by luisescobar89** [comment]
switches added on last version
